language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.3

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

env:
  - DB=mysql

before_script:
  - memcached -p 11211 &
  - cp .env.travis .env
  - mkdir -p tmp/pids
  - mkdir -p log
  - cd vendor && npm install
  - cd ../ && npm install -g istanbul codeclimate-test-reporter
  - bundle exec rake db:setup RAILS_ENV=test

script:
  - bundle exec rspec
