version: '2'

services:
  trialist:
    env_file: .env
    image: mfenner/trialist
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/home/app/webapp/app
      - ./config:/home/app/webapp/config
      - ./db:/home/app/webapp/db
      - ./spec:/home/app/webapp/spec
  db:
    env_file: .env
    image: mysql:5.6
    ports:
      - "3307:3306"
  memcached:
    image: memcached:1.4.31
